package Exceptions.ExceptionsPart2;

public class ExceptionsPart2 {
    public static void main(String[] args){
       // Scanner scanner = new Scanner(System.in);
       // while (true){
           // int x = Integer.parseInt(scanner.nextLine());

           // if (x != 0){
                //throw new ScannerExceptions("mmjmj");

                //try {
                  //  throw new IOException();
             //   }catch (IOException e){
              //      System.out.println("Пользоваетль ввел число не являющейся 0");

                }
            }


